kind: pipeline
type: ssh
name: default

server:
    host:
        from_secret: host
    user:
        from_secret: username
    ssh_key:
        from_secret: ssh_key
steps:
    - name: install node and dependencies
      commands:
        - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        - sudo apt-get install -y nodejs 
        # - sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash 
        # - export NVM_DIR="$HOME/.nvm" 11  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        # - nvm install v12.18.3 -y
        - mkdir ~/test
        - cp . -r ~/test
        - cd ~/test
        - npm install 
        - npm build

    - name: install nginx and reverse proxy
      commands:
        - sudo apt install nginx -y
        - mv ~/test/nginx_conf/default /etc/nginx/sites-enabled/
        - sudo service nginx restart